# The sequence of triangle numbers is generated by adding the natural numbers. So the th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 

# The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55

# Let us list the factors of the first seven triangle numbers:
# 1:    1
# 3:    1, 3
# 6:    1, 2, 3, 6
# 10:   1, 2, 5, 10
# 15:   1, 3, 5, 15
# 21:   1, 3, 7, 21
# 28:   1, 2, 4, 7, 14, 28

# We can see that  is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred divisors?

factors, factor_limit, num = 0, 500, 0
triangle_num = 0

while True:

    # get tringle number
    for i in range(num, 0, -1):
        triangle_num += i

    # Iterate from 1 up to the square root of the triangle
    for x in range(1, int((triangle_num**0.5)+1)):
        if (triangle_num % x == 0):
            factors += 1
            # Add the corresponding divisor (triangle_num/x) if it's not the same as x
            if(x*x != triangle_num):
                factors += 1
            print(f"Triangle Number:", triangle_num, "Total Factors:", factors, "Current Factor:", x)

    if(factors > factor_limit):
        print(f"500 divisor triangle number:", triangle_num, "Factors:", factors)
        break
    # reset the amount of factors for the next n'th triangle 
    else:
        factors = 0

    # DEBUG CODE
    # if num == 7:
    #     break
    # else:
    #     num += 1
    #     triangle_num = 0

    # increment n'th number & Reset triangle for next n'th number
    num += 1
    triangle_num = 0
